import Footer from "@/components/footer/Footer"
import Navbar from "@/components/navbar/Navbar"
import "./globals.css"
// import { Inter, Roboto, Poppins } from 'next/font/google'
// const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
